-- Tokyo Life 데이터베이스 초기 구성
-- 대상: PostgreSQL / tokyo_life / public
-- 전제: 기존 posts(id, title, content) 테이블만 존재
-- 기존 게시글을 유지하며 설계한 구조를 반영한다.
-- 한 번만 실행하는 변경 스크립트다.

BEGIN;

SET LOCAL search_path TO public;

-- ==================================================
-- 1. 관리자
-- ==================================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_username
        CHECK (username ~ '[^[:space:]]'),
    CONSTRAINT ck_users_display_name
        CHECK (display_name ~ '[^[:space:]]')
);

-- 기존 게시글의 작성자 연결을 위한 초기 계정.
-- 아래 값은 비밀번호 해시가 아닌 로그인 불가 표시다.
-- 로그인 구현 전에 실제 비밀번호 해시로 교체한다.
INSERT INTO users (username, password_hash, display_name)
VALUES ('admin', '!LOGIN_DISABLED!', 'hawie');


-- ==================================================
-- 2. 카테고리
-- ==================================================
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_categories_name UNIQUE (name),
    CONSTRAINT ck_categories_name
        CHECK (name ~ '[^[:space:]]'),
    CONSTRAINT ck_categories_display_order
        CHECK (display_order >= 0)
);

INSERT INTO categories (name, display_order)
VALUES
    ('여행·산책', 1),
    ('맛집·카페', 2),
    ('일본 생활', 3);


-- ==================================================
-- 3. 태그
-- ==================================================
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_tags_name UNIQUE (name),
    CONSTRAINT ck_tags_name
        CHECK (name ~ '[^[:space:]]')
);


-- ==================================================
-- 4. 기존 게시글 테이블 변경
-- ==================================================

-- 기존 id와 자동 증가 시퀀스는 유지한다.
ALTER TABLE posts
    ALTER COLUMN title TYPE VARCHAR(150),
    ALTER COLUMN content DROP NOT NULL;

ALTER TABLE posts
    ADD COLUMN author_id BIGINT,
    ADD COLUMN category_id BIGINT,
    ADD COLUMN summary VARCHAR(300),
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN published_at TIMESTAMPTZ;

-- 기존 글에는 작성자가 없으므로 초기 관리자와 연결한다.
UPDATE posts
SET author_id = (
    SELECT id
    FROM users
    WHERE username = 'admin'
);

-- 기존 데이터 연결 후 필수 입력 제약을 적용한다.
ALTER TABLE posts
    ALTER COLUMN author_id SET NOT NULL;

ALTER TABLE posts
    ADD CONSTRAINT fk_posts_author
        FOREIGN KEY (author_id)
        REFERENCES users (id)
        ON DELETE RESTRICT,

    ADD CONSTRAINT fk_posts_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
        ON DELETE RESTRICT,

    ADD CONSTRAINT ck_posts_title
        CHECK (title ~ '[^[:space:]]'),

    ADD CONSTRAINT ck_posts_status
        CHECK (status IN ('DRAFT', 'PUBLISHED')),

    ADD CONSTRAINT ck_posts_publish_requirements
        CHECK (
            status <> 'PUBLISHED'
            OR (
                category_id IS NOT NULL
                AND content IS NOT NULL
                AND content ~ '[^[:space:]]'
                AND published_at IS NOT NULL
            )
        );

-- 기존 데이터의 실제 생성 시점은 알 수 없으므로
-- created_at, updated_at에는 이번 변경 시점이 들어간다.


-- ==================================================
-- 5. 게시글·태그 연결
-- ==================================================
CREATE TABLE post_tags (
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    CONSTRAINT pk_post_tags
        PRIMARY KEY (post_id, tag_id),

    CONSTRAINT fk_post_tags_post
        FOREIGN KEY (post_id)
        REFERENCES posts (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_post_tags_tag
        FOREIGN KEY (tag_id)
        REFERENCES tags (id)
        ON DELETE CASCADE
);


-- ==================================================
-- 6. 게시글 이미지
-- ==================================================
CREATE TABLE post_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    alt_text VARCHAR(255),
    display_order INTEGER NOT NULL DEFAULT 0,
    is_cover BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_images_post
        FOREIGN KEY (post_id)
        REFERENCES posts (id)
        ON DELETE CASCADE,

    CONSTRAINT uq_post_images_storage_key
        UNIQUE (storage_key),

    CONSTRAINT ck_post_images_file_size
        CHECK (file_size > 0),

    CONSTRAINT ck_post_images_display_order
        CHECK (display_order >= 0)
);

-- 게시글당 대표 이미지 최대 1개
CREATE UNIQUE INDEX uq_post_images_one_cover
    ON post_images (post_id)
    WHERE is_cover = TRUE;


-- ==================================================
-- 7. 비회원 댓글
-- 기본안: 작성 즉시 공개, 관리자가 숨김 처리
-- ==================================================
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_comments_post
        FOREIGN KEY (post_id)
        REFERENCES posts (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_comments_nickname
        CHECK (nickname ~ '[^[:space:]]'),

    CONSTRAINT ck_comments_content
        CHECK (content ~ '[^[:space:]]'),

    CONSTRAINT ck_comments_status
        CHECK (status IN ('VISIBLE', 'HIDDEN'))
);


-- ==================================================
-- 8. 조회 및 외래키 관련 인덱스
-- PK와 UNIQUE에는 별도 인덱스를 중복 생성하지 않는다.
-- ==================================================
CREATE INDEX idx_posts_author_id
    ON posts (author_id);

CREATE INDEX idx_posts_category_id
    ON posts (category_id);

CREATE INDEX idx_posts_status_published_at
    ON posts (status, published_at DESC, id DESC);

CREATE INDEX idx_post_tags_tag_id
    ON post_tags (tag_id);

CREATE INDEX idx_post_images_post_order
    ON post_images (post_id, display_order, id);

CREATE INDEX idx_comments_post_status_created_at
    ON comments (post_id, status, created_at, id);

COMMIT;